### PR TITLE
Add fputcsv return value

### PR DESCRIPTION
**Pull request by kumamidori**
- Add fputcsv return value

### CODE REVIEW

**Comment by ajgarlag** [comment]
@kumamidori Thanks for your contribution, but I think you are mixing different concepts here. Please, open different Issues or PRs for each modification:
* Fix required version of `league/csv`
* Support for PHP 7.1, 7.2, and do not forget 7.3
* Add `fputcsv` return value

**Comment by kumamidori** [comment]
Thank you for your support !
I changed the PR title and modification to "Add fputcsv return value" only. Git rebased.
I open each other separately.

Is it a bit confusing because I change it later? If it is better to reissue this PR, please comment as such. I will put it out again.

**Comment by ajgarlag** [comment]
@kumamidori Rebase `master`, please.

**Comment by kumamidori** [comment]
Rebased latest `master` 😃

**Pull request merged**
